name: Setup Coder
description: An action to setup and configure Coder.
author: "Coder Technologies Inc. <https://coder.com>"

branding:
  icon: arrow-down-circle
  color: purple

inputs:
  access_url:
    description: "Coder access URL (e.g. https://coder.example.com)"
    required: true
  coder_session_token:
    description: "Coder session token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download and install Coder binary (Windows)
      if: runner.os == 'Windows'
      run: |
        if (${{ runner.arch }} -eq "ARM64") {
          $ARCH = "arm64"
        } else {
          $ARCH = "amd64"
        }
        curl -fsSL ${{ inputs.access_url }}/bin/coder-windows-$ARCH.exe -o $env:USERPROFILE\AppData\Local\bin\coder.exe
        echo "$env:USERPROFILE\AppData\Local\bin" >> $GITHUB_PATH
      shell: pwsh

    - name: Download and install Coder binary (Linux/macOS)
      if: runner.os != 'Windows'
      run: |
        if [ "${{ runner.arch }}" == "ARM64" ]; then
          ARCH="arm64"
        else
          ARCH="amd64"
        fi
        if [ "${{ runner.os }}" == "macOS" ]; then
          OS="darwin"
        else
          OS="linux"
        fi
        curl -fsSL ${{ inputs.access_url }}/bin/coder-${OS}-${ARCH} -o $HOME/.local/bin/coder
        chmod +x $HOME/.local/bin/coder
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Login to Coder (Windows)
      if: runner.os == 'Windows'
      run: coder login --token $CODER_SESSION_TOKEN $CODER_URL
      shell: pwsh
      env:
        CODER_URL: ${{ inputs.access_url }}
        CODER_SESSION_TOKEN: ${{ inputs.coder_session_token }}

    - name: Login to Coder (Linux/macOS)
      if: runner.os != 'Windows'
      run: coder login --token $CODER_SESSION_TOKEN $CODER_URL
      shell: bash
      env:
        CODER_URL: ${{ inputs.access_url }}
        CODER_SESSION_TOKEN: ${{ inputs.coder_session_token }}
