name: Setup Coder
description: An action to setup and configure Coder.
author: "Coder Technologies Inc. <https://coder.com>"

branding:
  icon: arrow-down-circle
  color: purple

inputs:
  access_url:
    description: "Coder access URL (e.g. https://coder.example.com)"
    required: true
  coder_session_token:
    description: "Coder session token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Coder binary from access URL (Windows)
      if: runner.os == 'Windows'
      run: |
        curl -fsSL ${{ inputs.access_url }}/bin/coder-windows-amd64.exe -o $env:USERPROFILE\AppData\Local\bin\coder.exe
        echo "$env:USERPROFILE\AppData\Local\bin" >> $GITHUB_PATH
      shell: pwsh

    - name: Download Coder binary from access URL (Linux)
      if: runner.os == 'Linux'
      run: |
        if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          ARCH="arm64"
        else
          ARCH="amd64"
        fi
        curl -fsSL ${{ inputs.access_url }}/bin/coder-linux-$ARCH -o $HOME/.local/bin/coder
        chmod +x $HOME/.local/bin/coder
        echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Download Coder binary from access URL (macOS)
      if: runner.os == 'macOS'
      run: |
        if [[ "$RUNNER_ARCH" == "ARM64" ]]; then
          ARCH="arm64"
        else
          ARCH="amd64"
        fi
        curl -fsSL ${{ inputs.access_url }}/bin/coder-darwin-$ARCH -o $HOME/.local/bin/coder
        chmod +x $HOME/.local/bin/coder
      shell: bash

    - name: Login to Coder
      shell: bash
      run: coder login --token $CODER_SESSION_TOKEN $CODER_URL
      env:
        CODER_URL: ${{ inputs.access_url }}
        CODER_SESSION_TOKEN: ${{ inputs.coder_session_token }}