name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Setup Coder Action
        uses: ./action.yaml
        with:
          access_url: ${{ secrets.CODER_URL }}
          coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}